[workspace]
members = [
  "3Sum",
  "Group Anagrams",
  "Longest Substring Without Repeating Characters",
  "Set Matrix Zeroes",
  "Longest Palindromic Substring",
  "Increasing Triplet Subsequence",
  "Count and Say",
]

[workspace.package]
license-file = "LICENSE"
authors = ["Evgeniy Malyutin <evxn@users.noreply.github.com>"]
