[package]
name = "binary_tree_right_side_view"
version = "0.1.0"
edition = "2021"
license-file.workspace = true
authors.workspace = true

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
