[package]
name = "count_and_say"
version = "0.1.0"
edition = "2021"
license-file.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
